library(caret)
data(mtcars)
head(mtcars)
model <- train(mpg ~ wt + qsec + am, method='lm', data = mtcars)
wt <- c(2.2)
qsec <- c(14.5)
am <- c(0)
mpg <- predict(model, data.frame(wt,qsec,am))
maxWt <- max(mtcars$wt)
